feed/urls.py
from django.urls import path, re_path

from . import views
from .categories import categories

app_name = 'feed'

category_re = r'^(?P<category>{})'.format('|'.join(categories))

urlpatterns = [
    path('', views.articles, name='frontpage'),
    re_path(category_re, views.articles, name='category'),
    path('favorite_article/<int:article_id>/',
            views.favorite_article, name='favorite_article'),
]

newsfeed/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('feed.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('favorites/', views.favorites, name='favorites'),
]

feed/models.py
from django.db import models

class Article(models.Model):
    category = models.CharField(max_length=100)
    title = models.TextField()
    source = models.TextField()
    description = models.TextField(null=True)
    url = models.URLField(null=True, max_length=1000)
    url_to_image = models.URLField(null=True, max_length=1000)
    pub_date = models.DateTimeField('date published', null=True)

    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from feed.models import Article

class User(AbstractUser):
    favorites = models.ManyToManyField(Article, default=None, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User

class UserRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password2'].label = 'Confirm password'

        self.fields['username'].help_text = 'Alphanumeric and @ / . / + / - / _ only.'
        self.fields['password2'].help_text = 'Just to be sure.'

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

feed/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import (HttpResponse, HttpResponseRedirect, redirect,
                              render)
from django.views.decorators.cache import never_cache

from .models import Article
from .tasks import refresh_articles

@never_cache
def articles(request, category='general'):
    articles = Article.objects.filter(
        category=category).order_by('-pub_date')

    if request.user.is_authenticated:
        set_if_favorite(request, articles)
    rows = partition_articles(articles, 2)

    paginator = Paginator(rows, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    wide_title, narrow_title = get_titles(category)
    context = {'category': category,
               'wide_title': wide_title,
               'narrow_title': narrow_title,
               'page_obj': page_obj}
    return render(request, 'feed/index.html', context)


@login_required
def favorite_article(request, article_id):
    article = Article.objects.filter(id=article_id).first()
    if request.user.favorites.filter(id=article_id).exists():
        request.user.favorites.remove(article)
        is_favorited = False
    else:
        request.user.favorites.add(article)
        is_favorited = True

    return HttpResponse(is_favorited)

def set_if_favorite(request, articles):
    for article in articles:
        if article in set(request.user.favorites.all()):
            article.favorited = True

def partition_articles(articles, n_cols):
    rows = []
    for i in range(0, len(articles), n_cols):
        row = articles[i: i + n_cols]
        rows.append(row)
    return rows

def get_titles(category):
    if category == 'general':
        return 'General', 'Newsfeed'
    return category.capitalize(), category.capitalize()

users/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate, logout

from .forms import UserRegisterForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')

            messages.success(request, f'Account {username} created')
            new_user = authenticate(username=username,
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            return redirect('feed:frontpage')
    else:
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)


def logout_view(request):
    logout(request)
    messages.success(request, f"You've been logged out.")
    return redirect('feed:frontpage')


def favorites(request):
    if not request.user.is_authenticated:
        return register(request)

    username = request.user.username
    articles = request.user.favorites.all()
    title = 'Favorites'

    context = {'wide_title': title, 'narrow_title': title, 'username': username, 'articles': articles}
    return render(request, 'users/favorites.html', context)

feed/templates/feed/index.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
<title>NewsFeed</title>
{% endblock %}

{% block scripts %}
<script src="{% static 'feed/favorite.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container-fluid" role="main" id="content">
    {% if messages %}
    {% for message in messages %}
    <div class="container-fluid mt-2 mb-0 alert alert-{{ message.tags }}" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}

    {% include 'title-bar.html' %}

    {% for row in page_obj %}
    <div class="row">
        {% for article in row %}
        <div class="col-md-6 mt-2">
            <div class="media">
                <div class="media-body">
                    <h5 class=""><a class="title" href="{{ article.url }}">{{ article.title }}</a></h5>
                    <small class="text-muted">{{ article.pub_date|naturaltime }} • </small>
                    {% if article.favorited %}
                    <button class="small text-muted favorite button-link" type="button" data="{{article.id}}">
                        unfavorite
                    </button>
                    {% else %}
                    <button class="small text-muted favorite button-link" type="button" data="{{article.id}}">
                        favorite
                    </button>
                    {% endif %}
                </div>
                {% if article.url_to_image != None %}
                <a href="{{ article.url }}"><img class="rounded mt-1 ml-2"
                        src="{{ article.url_to_image }}"></a>
                {% endif %}

            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
    <nav aria-label="pagination">
        <ul class="pagination mt-4">
            {% if page_obj.number|add:'-3' > 0 %}
                <li class="page-item"><a class="page-link" href="?page=1">
                    1
                </a></li>
            {% endif %}

            {% if page_obj.number == 5 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-3' }}">2</a></li>
            {% elif page_obj.number|add:'-3' > 0 and page_obj.number != 4 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-3' }}">&hellip;</a></li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="?page={{ num }}" aria-current="page">
                        page {{ page_obj.number }}
                    </a></li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">
                        {{ num }}
                    </a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.number|add:'4' == page_obj.paginator.num_pages %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'3' }}">{{ page_obj.number|add:'3' }}</a></li>
            {% elif page_obj.number|add:'2' < page_obj.paginator.num_pages and page_obj.number|add:'3' != page_obj.paginator.num_pages%}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'3' }}">&hellip;</a></li>
            {% endif %}

            {% if page_obj.number|add:'2' < page_obj.paginator.num_pages %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                        {{ page_obj.paginator.num_pages }}
                </a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %} {% endblock %}
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'feed/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'feed/custom.css' %}" rel="stylesheet">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    {% block css %} {% endblock %}

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'feed/jquery/jquery.min.js' %}" ></script>
    <script src="{% static 'feed/bootstrap/js/bootstrap.bundle.min.js' %}" ></script>

    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

    {% block scripts %} {% endblock %}

    <!-- For sidebar -->
    {% include 'sidebar.html' %}

</head>

<body>
    <div class="wrapper">
        <!-- Sidebar -->
        <nav class="navbar-light" id="sidebar">
            <a class="sidebar-brand" href="{% url 'feed:frontpage' %}">NewsFeed</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if category == 'entertainment' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'feed:category' 'entertainment' %}">Entertainment
                        {% if category == 'entertainment' %}
                        <span class="sr-only">(current)</span>
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item {% if category == 'business' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'feed:category' 'business' %}">Business
                        {% if category == 'business' %}
                        <span class="sr-only">(current)</span>
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item {% if category == 'health' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'feed:category' 'health' %}">Health
                        {% if category == 'health' %}
                        <span class="sr-only">(current)</span>
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item {% if category == 'science' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'feed:category' 'science' %}">Science
                        {% if category == 'science' %}
                        <span class="sr-only">(current)</span>
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item {% if category == 'technology' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'feed:category' 'technology' %}">Technology
                        {% if category == 'technology' %}
                        <span class="sr-only">(current)</span>
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item {% if category == 'sports' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'feed:category' 'sports' %}">Sports
                        {% if category == 'sports' %}
                        <span class="sr-only">(current)</span>
                        {% endif %}
                    </a>
                </li>
                <div class="dropdown-divider"></div>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:favorites' %}">Favorites</a>
                </li>
                <div class="dropdown-divider"></div>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link"">{{ request.user.username }}</a>
                                        </li>
                                        {% else %}
                                        <li class=" nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Sign up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
                {% endif %}
                <li class="nav-item nav-item-justify-bottom">
                    <a class="nav-link" href="https://newsapi.org"><div class="dark-link">powered by</div>NewsAPI.org</a>
                </li>
        </nav>


        <!-- Page Content -->
        {% block content %}{% endblock %}
    </div>

    <!-- Overlay element -->
    <div class="opacity-transition" id="overlay"></div>
</body>

</html>

templates/sidebar.html
        <script type="text/javascript">
                $(document).ready(function () {
                    $('#overlay').on('click', function () {
                        // hide sidebar
                        $('#sidebar').removeClass('active');
                        // hide overlay
                        $('#overlay').removeClass('active');
                        $('#sidebarCollapse').toggleClass('active');
                    });

                    $('#sidebarCollapse').on('click', function () {
                        // open sidebar
                        $('#sidebar').addClass('active');
                        // fade in the overlay
                        $('#overlay').addClass('active');
                        $(this).toggleClass('active');
                    });
                });
        </script>

templates/title-bar.html
<div class="row">
    <div class="col mt-3 mb-1">
        <h4>
            <span class="wide-text">{{ wide_title }}</span>
            <span class="narrow-text">{{ narrow_title }}</span>
        </h4>
    </div>

    <div class="col-auto mt-2 mb-1">
        <button id="sidebarCollapse">
            <span></span>
            <span></span>
            <span></span>
        </button>
    </div>
</div>

users/templates/users/favorites.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>NewsFeed - Favorites</title>
{% endblock %}

{% block css %}
<link href="{% static 'users/custom.css' %}" rel="stylesheet">
{% endblock %}

{% block scripts %}
<script src="{% static 'users/favorite.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container-fluid" role="main" id="content">
    {% include 'title-bar.html' %}
    {% for article in articles %}
    <div class="row mt-1 mb-1 {% if forloop.counter|divisibleby:2 %}bg-light{% endif %}">
        <div class="col col-lg-10">
            <a class="fav-title" href="{{ article.url }}">{{ article.title }}<a>
        </div>
        <div class="col-auto">
            <button class="favorite btn btn-sm btn-danger" type="button" data="{{article.id}}">
                unfavorite
            </button>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>NewsFeed - Log in</title>
{% endblock %}

{% block css %}
    <link href="{% static 'users/custom.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<form class="form-signin" method="POST">
    {% csrf_token %}
    <h3 class="text-center mb-3">Log in</h3>
    <fieldset class="form-group">
        {% crispy form %}
        <div class="form-group">
            <button class="btn btn-lg btn-outline-primary float-right" type="submit">Log in</button>
        </div>
        <p class="text-muted pt-4">
            Don't have an account? <a class="ml-1" href="{% url 'users:register' %}">Sign up</a>
        </p>
    </fieldset>

</form>
{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>NewsFeed - Sign up</title>
{% endblock %}

{% block css %}
    <link href="{% static 'users/custom.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

        <form class="form-signin" method="POST">
            {% csrf_token %}
            <h3 class="text-center mb-3">Make an account</h3>
            <fieldset class="form-group">
                {% crispy form %}
                <div class="form-group">
                    <button class="btn btn-lg btn-outline-primary float-right" type="submit">Sign up</button>
                </div>
                <p class="text-muted pt-4">
                    Already have an account? <a class="ml-1" href="{% url 'users:login' %}">Log in</a>
                </p>
            </fieldset>
        </form>

{% endblock %}